<?php 

/*
 * Define Advanced Custom Fields for Homebase 
 */
function bloglike_acf_fields() {

  acf_add_local_field_group(array(
    'key' => 'group_bloglike',
    'title' => 'Template: Like a blog',
    'fields' => array(
      array(
        'key' => 'field_bloglike_flexible_content',
        'label' => 'Flexible content',
        'name' => 'flexible_content',
        'type' => 'flexible_content',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layouts' => array(
			'layout_bloglike_simple_one_column' => array(
				'key' => 'layout_bloglike_simple_one_column',
				'name' => 'simple_one_column',
				'label' => 'Simple one column',
				'display' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_bloglike_simple_one_column_hide_widget',
						'label' => 'Visibility',
						'name' => 'hide_widget',
						'aria-label' => '',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'message' => 'Hide widget',
						'default_value' => 0,
						'ui' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_bloglike_simple_one_column_widget_id',
						'label' => 'Widget ID',
						'name' => 'widget_id',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_bloglike_simple_one_column_content',
						'label' => 'Content',
						'name' => 'content',
						'aria-label' => '',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 0,
					),
				),
				'min' => '',
				'max' => '',
			),
			'layout_bloglike_sub_cat_nav' => array(
	            'key' => 'layout_bloglike_sub_cat_nav',
	            'name' => 'flex_sub_cat_nav',
	            'label' => 'Sub Category Navbar',
	            'display' => 'block',
	            'sub_fields' => array(
	            	array(
		                'key' => 'field_bloglike_sub_cat_nav_hide_widget',
		                'label' => 'Visibility',
		                'name' => 'hide_widget',
		                'type' => 'true_false',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '33.3',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'message' => 'Hide widget',
		                'default_value' => 0,
		                'ui' => 0,
		                'ui_on_text' => '',
		                'ui_off_text' => '',
	            	),
	            	array(
		                'key' => 'field_bloglike_sub_cat_nav_hide_searchbar',
		                'label' => 'Hide SearchBar',
		                'name' => 'hide_searchbar',
		                'type' => 'true_false',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '33.3',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'message' => '',
		                'default_value' => 0,
		                'ui' => 0,
		                'ui_on_text' => '',
		                'ui_off_text' => '',
	            	),
		            array(
		                'key' => 'field_bloglike_sub_cat_nav_hide_nav_menu',
		                'label' => 'Hide Nav Menu',
		                'name' => 'hide_nav_menu',
		                'type' => 'true_false',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '33.3',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'message' => '',
		                'default_value' => 1,
		                'ui' => 0,
		                'ui_on_text' => '',
		                'ui_off_text' => '',
		            ),
		            array(
		                'key' => 'field_bloglike_sub_cat_nav_search_placeholder',
		                'label' => 'Placeholder',
		                'name' => 'search_placeholder',
		                'type' => 'text',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => array(
		                  array(
		                    array(
		                      'field' => 'field_bloglike_sub_cat_nav_hide_searchbar',
		                      'operator' => '!=',
		                      'value' => '1',
		                    ),
		                  ),
		                ),
		                'wrapper' => array(
		                  'width' => '',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'default_value' => 'Search',
		                'placeholder' => '',
		                'prepend' => '',
		                'append' => '',
		                'maxlength' => '',
		            ),
		            array(
		                'key' => 'field_bloglike_sub_cat_nav_navbar_headline',
		                'label' => 'Navbar Headline',
		                'name' => 'navbar_headline',
		                'type' => 'text',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'default_value' => '',
		                'placeholder' => '',
		                'prepend' => '',
		                'append' => '',
		                'maxlength' => '',
		            ),
	            ),
	            'min' => '',
	            'max' => '',
	        ),
			'layout_bloglike_spectext' => array(
	            'key' => 'layout_bloglike_spectext',
	            'name' => 'flex_spectext',
	            'label' => 'Specific Text Widget',
	            'display' => 'block',
	            'sub_fields' => array(
		            array(
		                'key' => 'field_bloglike_spectext_hide_widget',
		                'label' => 'Visibility',
		                'name' => 'hide_widget',
		                'type' => 'true_false',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '50',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'message' => 'Hide widget',
		                'default_value' => 0,
		                'ui' => 0,
		                'ui_on_text' => '',
		                'ui_off_text' => '',
		            ),
		            array(
		                'key' => 'field_bloglike_spectext_add_border_top',
		                'label' => 'Add border top',
		                'name' => 'add_border_top',
		                'type' => 'true_false',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '50',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'message' => '',
		                'default_value' => 0,
		                'ui' => 0,
		                'ui_on_text' => '',
		                'ui_off_text' => '',
		            ),
		            array(
		                'key' => 'field_bloglike_spectext_widget_type',
		                'label' => 'Widget Type',
		                'name' => 'widget_type',
		                'type' => 'radio',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '50',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'choices' => array(
		                  'withoutlogo' => 'Without Logo',
		                  'withlogo' => 'With Logo',
		                ),
		                'allow_null' => 0,
		                'other_choice' => 0,
		                'save_other_choice' => 0,
		                'default_value' => '',
		                'layout' => 'horizontal',
		                'return_format' => 'value',
		            ),
		            array(
		                'key' => 'field_bloglike_spectext_text_align',
		                'label' => 'Text Align',
		                'name' => 'text_align',
		                'type' => 'radio',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '50',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'choices' => array(
		                  'text-left' => 'Left',
		                  'text-center' => 'Center',
		                  'text-right' => 'Right',
		                ),
		                'allow_null' => 0,
		                'other_choice' => 0,
		                'save_other_choice' => 0,
		                'default_value' => '',
		                'layout' => 'horizontal',
		                'return_format' => 'value',
		            ),
		            array(
		                'key' => 'field_bloglike_spectext_logo',
		                'label' => 'Logo',
		                'name' => 'logo',
		                'type' => 'image',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => array(
		                  array(
		                    array(
		                      'field' => 'field_bloglike_spectext_widget_type',
		                      'operator' => '==',
		                      'value' => 'withlogo',
		                    ),
		                  ),
		                ),
		                'wrapper' => array(
		                  'width' => '',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'return_format' => 'array',
		                'preview_size' => 'thumbnail',
		                'library' => 'all',
		                'min_width' => '',
		                'min_height' => '',
		                'min_size' => '',
		                'max_width' => '',
		                'max_height' => '',
		                'max_size' => '',
		                'mime_types' => '',
		            ),
		            array(
		                'key' => 'field_bloglike_spectext_text',
		                'label' => 'Text',
		                'name' => 'text',
		                'type' => 'wysiwyg',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'default_value' => '',
		                'tabs' => 'all',
		                'toolbar' => 'full',
		                'media_upload' => 1,
		                'delay' => 0,
		            ),
	            ),
	            'min' => '',
	            'max' => '',
          	),
			'layout_bloglike_post_grid' => array(
	            'key' => 'layout_bloglike_post_grid',
	            'name' => 'flex_post_grid',
	            'label' => 'Post Grid',
	            'display' => 'block',
	            'sub_fields' => array(
		            array(
		                'key' => 'field_bloglike_post_grid_hide_widget',
		                'label' => 'Visibility',
		                'name' => 'hide_widget',
		                'type' => 'true_false',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '33',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'message' => 'Hide widget',
		                'default_value' => 0,
		                'ui' => 0,
		                'ui_on_text' => '',
		                'ui_off_text' => '',
		            ),
		            array(
		                'key' => 'field_bloglike_post_grid_sort_by',
		                'label' => 'Sort by',
		                'name' => 'sort_by',
		                'type' => 'select',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '33',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'choices' => array(
		                  'latest' => 'Latest',
		                  'popular' => 'Popular',
		                  'custom' => 'Custom',
		                ),
		                'default_value' => array(
		                ),
		                'allow_null' => 0,
		                'multiple' => 0,
		                'ui' => 0,
		                'ajax' => 0,
		                'return_format' => 'value',
		                'placeholder' => '',
		            ),
		            array(
		                'key' => 'field_bloglike_post_grid_custom_selector',
		                'label' => 'Custom selector',
		                'name' => 'custom_selector',
		                'type' => 'text',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '33',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'default_value' => '',
		                'placeholder' => '',
		                'prepend' => '',
		                'append' => '',
		                'maxlength' => '',
		            ),
		            array(
		                'key' => 'field_bloglike_post_grid_headline',
		                'label' => 'Headline',
		                'name' => 'headline',
		                'type' => 'text',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'default_value' => '',
		                'placeholder' => '',
		                'prepend' => '',
		                'append' => '',
		                'maxlength' => '',
		            ),
		            array(
		                'key' => 'field_bloglike_post_grid_posts_count',
		                'label' => 'Number of posts',
		                'name' => 'posts_count',
		                'type' => 'number',
		                'instructions' => 'If this gird includes a subscribe widget, please reduce the number of posts by 1',
		                'required' => 0,
		                'conditional_logic' => array(
		                  array(
		                    array(
		                      'field' => 'field_bloglike_post_grid_sort_by',
		                      'operator' => '!=',
		                      'value' => 'custom',
		                    ),
		                  ),
		                ),
		                'wrapper' => array(
		                  'width' => '',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'default_value' => 9,
		                'placeholder' => '',
		                'prepend' => '',
		                'append' => '',
		                'min' => 3,
		                'max' => '',
		                'step' => '',
		            ),
		            array(
		                'key' => 'field_bloglike_post_grid_custom_posts',
		                'label' => 'Custom Posts',
		                'name' => 'custom_posts',
		                'type' => 'relationship',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => array(
		                  array(
		                    array(
		                      'field' => 'field_bloglike_post_grid_sort_by',
		                      'operator' => '==',
		                      'value' => 'custom',
		                    ),
		                  ),
		                ),
		                'wrapper' => array(
		                  'width' => '',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'post_type' => array(
		                  0 => 'post',
		                ),
		                'taxonomy' => '',
		                'filters' => array(
		                  0 => 'search',
		                  1 => 'post_type',
		                  2 => 'taxonomy',
		                ),
		                'elements' => '',
		                'min' => 3,
		                'max' => '',
		                'return_format' => 'object',
		            ),
	            ),
	            'min' => '',
	            'max' => '',
	        ),
			'layout_bloglike_post_slider' => array(
	            'key' => 'layout_bloglike_post_slider',
	            'name' => 'flex_post_slider',
	            'label' => 'Post slider',
	            'display' => 'block',
	            'sub_fields' => array(
		            array(
		                'key' => 'field_bloglike_post_slider_hide_widget',
		                'label' => 'Visibility',
		                'name' => 'hide_widget',
		                'type' => 'true_false',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '33',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'message' => 'Hide widget',
		                'default_value' => 0,
		                'ui' => 0,
		                'ui_on_text' => '',
		                'ui_off_text' => '',
		            ),
		            array(
		                'key' => 'field_bloglike_post_slider_sort_by',
		                'label' => 'Sort by',
		                'name' => 'sort_by',
		                'type' => 'select',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '33',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'choices' => array(
		                  'latest' => 'Latest',
		                  'popular' => 'Popular',
		                  'custom' => 'Custom',
		                  'related' => 'Related',
		                ),
		                'default_value' => array(
		                ),
		                'allow_null' => 0,
		                'multiple' => 0,
		                'ui' => 0,
		                'return_format' => 'value',
		                'ajax' => 0,
		                'placeholder' => '',
		            ),
		            array(
		                'key' => 'field_bloglike_post_slider_custom_selector',
		                'label' => 'Custom selector',
		                'name' => 'custom_selector',
		                'type' => 'text',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '33',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'default_value' => '',
		                'placeholder' => '',
		                'prepend' => '',
		                'append' => '',
		                'maxlength' => '',
		            ),
		            array(
		                'key' => 'field_bloglike_post_slider_headline',
		                'label' => 'Headline',
		                'name' => 'headline',
		                'type' => 'text',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'default_value' => '',
		                'placeholder' => '',
		                'prepend' => '',
		                'append' => '',
		                'maxlength' => '',
		            ),
		            array(
		                'key' => 'field_bloglike_post_slider_custom_posts',
		                'label' => 'Custom Posts',
		                'name' => 'custom_posts',
		                'type' => 'relationship',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => array(
		                  array(
		                    array(
		                      'field' => 'field_bloglike_post_slider_sort_by',
		                      'operator' => '==',
		                      'value' => 'custom',
		                    ),
		                  ),
		                ),
		                'wrapper' => array(
		                  'width' => '',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'post_type' => array(
		                  0 => 'post',
		                ),
		                'taxonomy' => '',
		                'filters' => array(
		                  0 => 'search',
		                  1 => 'post_type',
		                  2 => 'taxonomy',
		                ),
		                'elements' => '',
		                'min' => 4,
		                'max' => '',
		                'return_format' => 'object',
		            ),
		            array(
		                'key' => 'field_bloglike_post_slider_posts_count',
		                'label' => 'Number of posts',
		                'name' => 'posts_count',
		                'type' => 'number',
		                'instructions' => 'Post slider\'s minimum number of posts is 4.',
		                'required' => 0,
		                'conditional_logic' => array(
		                  array(
		                    array(
		                      'field' => 'field_bloglike_post_slider_sort_by',
		                      'operator' => '!=',
		                      'value' => 'custom',
		                    ),
		                  ),
		                ),
		                'wrapper' => array(
		                  'width' => '',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'default_value' => 4,
		                'placeholder' => '',
		                'prepend' => '',
		                'append' => '',
		                'min' => 4,
		                'max' => '',
		                'step' => '',
		            ),
	            ),
	            'min' => '',
	            'max' => '',
        	),
			'layout_bloglike_subscribe_widget' => array(
	            'key' => 'layout_bloglike_subscribe_widget',
	            'name' => 'flex_subscrible_widget',
	            'label' => 'Subscribe Widget',
	            'display' => 'block',
	            'sub_fields' => array(
		            array(
		                'key' => 'field_bloglike_subscribe_widget_visibility',
		                'label' => 'Visibility',
		                'name' => 'visibility',
		                'type' => 'true_false',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '50',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'message' => 'Hide widget',
		                'default_value' => 0,
		                'ui' => 0,
		                'ui_on_text' => '',
		                'ui_off_text' => '',
		            ),
		            array(
		                'key' => 'field_bloglike_subscribe_widget_type',
		                'label' => 'Type',
		                'name' => 'type',
		                'type' => 'radio',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '50',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'choices' => array(
		                  'full' => 'Full Width',
		                  'box' => 'Boxed',
		                ),
		                'allow_null' => 0,
		                'other_choice' => 0,
		                'save_other_choice' => 0,
		                'default_value' => '',
		                'layout' => 'horizontal',
		                'return_format' => 'value',
		            ),
		            array(
		                'key' => 'field_bloglike_subscribe_widget_headline',
		                'label' => 'Headline',
		                'name' => 'headline',
		                'type' => 'text',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'default_value' => '',
		                'placeholder' => '',
		                'prepend' => '',
		                'append' => '',
		                'maxlength' => '',
		            ),
		            array(
		                'key' => 'field_bloglike_subscribe_widget_subheadline',
		                'label' => 'Subheadline',
		                'name' => 'subheadline',
		                'type' => 'text',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'default_value' => '',
		                'placeholder' => '',
		                'prepend' => '',
		                'append' => '',
		                'maxlength' => '',
		            ),
		            array(
		                'key' => 'field_bloglike_subscribe_widget_button_text',
		                'label' => 'Button Text',
		                'name' => 'button_text',
		                'type' => 'text',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '50',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'default_value' => 'Submit',
		                'placeholder' => '',
		                'prepend' => '',
		                'append' => '',
		                'maxlength' => '',
		            ),
		            array(
		                'key' => 'field_bloglike_subscribe_widget_form_link',
		                'label' => 'Form Link',
		                'name' => 'form_link',
		                'type' => 'text',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '50',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'default_value' => '',
		                'placeholder' => '',
		                'prepend' => '',
		                'append' => '',
		                'maxlength' => '',
		            ),
		            array(
		                'key' => 'field_bloglike_subscribe_widget_modal_message',
		                'label' => 'Modal message',
		                'name' => 'modal_message',
		                'type' => 'text',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '33.3',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'default_value' => 'Thanks for subscribing',
		                'placeholder' => '',
		                'prepend' => '',
		                'append' => '',
		                'maxlength' => '',
		            ),
		            array(
		                'key' => 'field_bloglike_subscribe_widget_modal_btn_text',
		                'label' => 'Modal button text',
		                'name' => 'modal_btn_text',
		                'type' => 'text',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '33.3',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'default_value' => 'OK',
		                'placeholder' => '',
		                'prepend' => '',
		                'append' => '',
		                'maxlength' => '',
		            ),
		            array(
		                'key' => 'field_bloglike_subscribe_widget_modal_ID',
		                'label' => 'Modal ID',
		                'name' => 'modal_ID',
		                'type' => 'text',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '33.3',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'default_value' => '',
		                'placeholder' => '',
		                'prepend' => '',
		                'append' => '',
		                'maxlength' => '',
		            ),
	            ),
	            'min' => '',
	            'max' => '',
	        ),
			'layout_bloglike_bottom_cta' => array(
	            'key' => 'layout_bloglike_bottom_cta',
	            'name' => 'post_bottom_cta',
	            'label' => 'Bottom CTA',
	            'display' => 'block',
	            'sub_fields' => array(
		            array(
		                'key' => 'field_bloglike_bottom_cta_visibility',
		                'label' => 'Visibility',
		                'name' => 'hide_widget',
		                'type' => 'true_false',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'message' => 'Hide widget',
		                'default_value' => 0,
		                'ui' => 0,
		                'ui_on_text' => '',
		                'ui_off_text' => '',
		            ),
		            array(
		                'key' => 'field_bloglike_bottom_cta_text',
		                'label' => 'Text',
		                'name' => 'text',
		                'type' => 'text',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'default_value' => '',
		                'placeholder' => '',
		                'prepend' => '',
		                'append' => '',
		                'maxlength' => '',
		            ),
		            array(
		                'key' => 'field_bloglike_bottom_cta_button_text',
		                'label' => 'Button Text',
		                'name' => 'button_text',
		                'type' => 'text',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '50',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'default_value' => '',
		                'placeholder' => '',
		                'prepend' => '',
		                'append' => '',
		                'maxlength' => '',
		            ),
		            array(
		                'key' => 'field_bloglike_bottom_cta_button_link',
		                'label' => 'Button Link',
		                'name' => 'button_link',
		                'type' => 'text',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '50',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'default_value' => '',
		                'placeholder' => '',
		                'prepend' => '',
		                'append' => '',
		                'maxlength' => '',
		            ),
	            ),
	            'min' => '',
	            'max' => '',
	        ),
	        'layout_bloglike_faq' => array(
	            'key' => 'layout_bloglike_faq',
	            'name' => 'flex_faq',
	            'label' => 'FAQs widget',
	            'display' => 'block',
	            'sub_fields' => array(
		            array(
		                'key' => 'field_bloglike_faq_hide_widget',
		                'label' => 'Visibility',
		                'name' => 'hide_widget',
		                'type' => 'true_false',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '50',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'message' => 'Hide widget',
		                'default_value' => 0,
		                'ui' => 0,
		                'ui_on_text' => '',
		                'ui_off_text' => '',
		            ),
		            array(
		                'key' => 'field_bloglike_faq_widget_id',
		                'label' => 'Widget ID',
		                'name' => 'widget_id',
		                'type' => 'text',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '50',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'default_value' => '',
		                'placeholder' => '',
		                'prepend' => '',
		                'append' => '',
		                'maxlength' => '',
		            ),
		            array(
		                'key' => 'field_bloglike_faq_left',
		                'label' => 'Left',
		                'name' => '',
		                'type' => 'tab',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'placement' => 'top',
		                'endpoint' => 0,
		            ),
		            array(
		                'key' => 'field_bloglike_faq_left_headline',
		                'label' => 'Headline',
		                'name' => 'headline',
		                'type' => 'text',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'default_value' => '',
		                'placeholder' => '',
		                'prepend' => '',
		                'append' => '',
		                'maxlength' => '',
		            ),
		            array(
		                'key' => 'field_bloglike_faq_left_image_d',
		                'label' => 'Image (Desktop)',
		                'name' => 'image_d',
		                'type' => 'image',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '50',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'return_format' => 'id',
		                'preview_size' => 'medium',
		                'library' => 'all',
		                'min_width' => '',
		                'min_height' => '',
		                'min_size' => '',
		                'max_width' => '',
		                'max_height' => '',
		                'max_size' => '',
		                'mime_types' => '',
		            ),
		            array(
		                'key' => 'field_bloglike_faq_left_image_m',
		                'label' => 'Image (Mobile)',
		                'name' => 'image_m',
		                'type' => 'image',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '50',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'return_format' => 'id',
		                'preview_size' => 'medium',
		                'library' => 'all',
		                'min_width' => '',
		                'min_height' => '',
		                'min_size' => '',
		                'max_width' => '',
		                'max_height' => '',
		                'max_size' => '',
		                'mime_types' => '',
		            ),
		            array(
		                'key' => 'field_bloglike_faq_right',
		                'label' => 'Right',
		                'name' => '',
		                'type' => 'tab',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'placement' => 'top',
		                'endpoint' => 0,
		            ),
		            array(
		                'key' => 'field_bloglike_faq_right_faqs',
		                'label' => 'FAQs',
		                'name' => 'faqs',
		                'type' => 'repeater',
		                'instructions' => '',
		                'required' => 0,
		                'conditional_logic' => 0,
		                'wrapper' => array(
		                  'width' => '',
		                  'class' => '',
		                  'id' => '',
		                ),
		                'collapsed' => '',
		                'min' => 0,
		                'max' => 0,
		                'layout' => 'block',
		                'button_label' => '',
		                'sub_fields' => array(
		                  array(
		                    'key' => 'field_bloglike_faq_right_faqs_faq_field',
		                    'label' => 'FAQ field',
		                    'name' => 'faq_field',
		                    'type' => 'text',
		                    'instructions' => '',
		                    'required' => 0,
		                    'conditional_logic' => 0,
		                    'wrapper' => array(
		                      'width' => '',
		                      'class' => '',
		                      'id' => '',
		                    ),
		                    'default_value' => '',
		                    'placeholder' => '',
		                    'prepend' => '',
		                    'append' => '',
		                    'maxlength' => '',
		                  ),
		                  array(
		                    'key' => 'field_bloglike_faq_right_faqs_question',
		                    'label' => 'Question',
		                    'name' => 'question',
		                    'type' => 'text',
		                    'instructions' => '',
		                    'required' => 0,
		                    'conditional_logic' => 0,
		                    'wrapper' => array(
		                      'width' => '50',
		                      'class' => '',
		                      'id' => '',
		                    ),
		                    'default_value' => '',
		                    'placeholder' => '',
		                    'prepend' => '',
		                    'append' => '',
		                    'maxlength' => '',
		                  ),
		                  array(
		                    'key' => 'field_bloglike_faq_right_faqs_answers',
		                    'label' => 'Answers',
		                    'name' => 'answers',
		                    'type' => 'wysiwyg',
		                    'instructions' => '',
		                    'required' => 0,
		                    'conditional_logic' => 0,
		                    'wrapper' => array(
		                      'width' => '50',
		                      'class' => '',
		                      'id' => '',
		                    ),
		                    'default_value' => '',
		                    'tabs' => 'all',
		                    'toolbar' => 'full',
		                    'media_upload' => 1,
		                    'delay' => 0,
		                  ),
		                ),
		            ),
	            ),
	            'min' => '',
	            'max' => '',
	        ),
			'layout_bloglike_mto' => array(
	            'key' => 'layout_bloglike_mto',
	            'name' => 'flex_mto',
	            'label' => 'Meet the owners',
	            'display' => 'block',
	            'sub_fields' => array(
		            array(
						'key' => 'layout_bloglike_mto_hide_widget',
						'label' => 'Visibility',
						'name' => 'mto_hide_widget',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => 'Hide widget',
						'default_value' => 0,
						'ui' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'layout_bloglike_mto_meet_the_owners_row',
						'label' => 'Meet the owners (row)',
						'name' => 'meet_the_owners_row',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'collapsed' => '',
						'min' => 0,
						'max' => 0,
						'layout' => 'block',
						'button_label' => '',
						'sub_fields' => array(
							array(
								'key' => 'layout_bloglike_mto_meet_the_owners_row_mto_image',
								'label' => 'Image',
								'name' => 'mto_image',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '30',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => 'medium',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
							array(
								'key' => 'layout_bloglike_mto_meet_the_owners_row_mto_name',
								'label' => 'Name',
								'name' => 'mto_name',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '30',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'layout_bloglike_mto_meet_the_owners_row_mto_company',
								'label' => 'Company',
								'name' => 'mto_company',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '40',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'layout_bloglike_mto_meet_the_owners_row_mto_text',
								'label' => 'Text',
								'name' => 'mto_text',
								'type' => 'textarea',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'maxlength' => '',
								'rows' => '',
								'new_lines' => '',
							),
						),
					),
	            ),
	            'min' => '',
	            'max' => '',
	        ),
        ),
        'button_label' => 'Add Row',
        'min' => '',
        'max' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'page_template',
          'operator' => '==',
          'value' => 'templates/flexible-bloglike.php',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
  ));
  
}

if ( function_exists('acf_add_local_field_group') ) add_action('acf/init', 'bloglike_acf_fields');  