<?php 

/*
 * Define Advanced Custom Fields for Homebase 
 */
function flexible_subscribe_success_mt192_fields() {
	acf_add_local_field_group(array(
		'key' => 'group_62ebdbb5bcbfb',
		'title' => 'Template: Subscribe Success MT192',
		'fields' => array(
			array(
				'key' => 'field_62ebdbe0bd17c',
				'label' => 'Flexible content',
				'name' => 'flexible_content',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layouts' => array(
					'layout_62ebdbee12660' => array(
						'key' => 'layout_62ebdbee12660',
						'name' => 'subscribe_success_hero',
						'label' => 'Subscribe Success Hero',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_62ebdbf9bd17d',
								'label' => 'Subscribe Success Hero',
								'name' => '',
								'type' => 'tab',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'placement' => 'top',
								'endpoint' => 0,
							),
							array(
								'key' => 'field_62ebdc3ebd180',
								'label' => 'Hero image',
								'name' => 'hero_image',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => 'medium',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
							array(
								'key' => 'field_62ebdc2cbd17e',
								'label' => 'Headline',
								'name' => 'headline',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_62ebdc36bd17f',
								'label' => 'Subheadline',
								'name' => 'subheadline',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_62ebdc83acba4' => array(
						'key' => 'layout_62ebdc83acba4',
						'name' => 'quick_links',
						'label' => 'Quick links',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_62ebdcafacba5',
								'label' => 'Quick links',
								'name' => '',
								'type' => 'tab',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'placement' => 'top',
								'endpoint' => 0,
							),
							array(
								'key' => 'field_62ebdcc4acba6',
								'label' => 'Headline',
								'name' => 'headline',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_62ebdcc8acba7',
								'label' => 'Subheadline',
								'name' => 'subheadline',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_62ebdccdacba8',
								'label' => 'Link blocks',
								'name' => 'link_blocks',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'collapsed' => '',
								'min' => 3,
								'max' => 3,
								'layout' => 'table',
								'button_label' => '',
								'sub_fields' => array(
									array(
										'key' => 'field_62ebdce3acba9',
										'label' => 'Block icon',
										'name' => 'block_icon',
										'type' => 'image',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'array',
										'preview_size' => 'medium',
										'library' => 'all',
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
									),
									array(
										'key' => 'field_62ebdd04acbaa',
										'label' => 'Text',
										'name' => 'text',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_62ebdd0facbab',
										'label' => 'Link',
										'name' => 'link',
										'type' => 'link',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'array',
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
				),
				'button_label' => 'Add Row',
				'min' => '',
				'max' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_template',
					'operator' => '==',
					'value' => 'templates/flexible-subscribe-success-mt192.php',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));
}

if ( function_exists('acf_add_local_field_group') ) add_action('acf/init', 'flexible_subscribe_success_mt192_fields');  