<?php 

/*
 * Define Advanced Custom Fields for Homebase 
 */
function flexible_influencers_lp_acf_fields() {

  acf_add_local_field_group(array(
    'key' => 'group_influencers',
    'title' => 'Template: Influencers LP',
    'fields' => array(
      array(
        'key' => 'field_influencers_flexible_content',
        'label' => 'Flexible content',
        'name' => 'flexible_content',
        'type' => 'flexible_content',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layouts' => array(
          'layout_influencers_flex_hero' => array(
            'key' => 'layout_influencers_flex_hero',
            'name' => 'flex_hero',
            'label' => 'Hero',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_influencers_flex_hero_hide_widget',
                'label' => 'Visibility',
                'name' => 'hide_widget',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '16.66%',
                  'class' => '',
                  'id' => '',
                ),
                'message' => 'Hide widget',
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
              ),
              array(
                'key' => 'field_influencers_flex_hero_widget_id',
                'label' => 'Widget ID',
                'name' => 'widget_id',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '16.66%',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_influencers_flex_hero_widget_class',
                'label' => 'Widget class',
                'name' => 'widget_class',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '16.66%',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_influencers_flex_hero_add_background',
                'label' => 'Add background',
                'name' => 'add_background',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '25',
                  'class' => '',
                  'id' => '',
                ),
                'message' => 'Add a half circle background image',
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
              ),
              array(
                'key' => 'field_influencers_flex_hero_bg_color',
                'label' => 'Bg color',
                'name' => 'bg_color',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                  array(
                    array(
                      'field' => 'field_influencers_flex_hero_add_background',
                      'operator' => '==',
                      'value' => '1',
                    ),
                  ),
                ),
                'wrapper' => array(
                  'width' => '25',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array(
                  'teal' => 'Teal',
                  'lpink' => 'Light Pink',
                ),
                'default_value' => 'teal',
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
              ),
              array(
                'key' => 'field_influencers_flex_hero_left',
                'label' => 'Left',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
              ),
              array(
                'key' => 'field_influencers_flex_hero_add_l_margin',
                'label' => 'Add left margin',
                'name' => 'add_l_margin',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
              ),
              array(
                'key' => 'field_influencers_flex_hero_seo_title',
                'label' => 'SEO title',
                'name' => 'seo_title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_influencers_flex_hero_headline',
                'label' => 'Headline',
                'name' => 'headline',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_influencers_flex_hero_subheadline',
                'label' => 'Subheadline',
                'name' => 'subheadline',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_influencers_flex_hero_coupon_headline',
                'label' => 'Coupon headline',
                'name' => 'coupon_headline',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_influencers_flex_hero_coupon_subheadline',
                'label' => 'Coupon subheadline',
                'name' => 'coupon_subheadline',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_influencers_flex_hero_coupon_caption',
                'label' => 'Coupon caption',
                'name' => 'coupon_caption',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_influencers_flex_hero_cta_type',
                'label' => 'CTA type',
                'name' => 'cta_type',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array(
                  'form' => 'Form',
                  'button' => 'Button',
                ),
                'allow_null' => 0,
                'other_choice' => 0,
                'default_value' => 'form',
                'layout' => 'horizontal',
                'return_format' => 'value',
                'save_other_choice' => 0,
              ),
              array(
                'key' => 'field_influencers_flex_hero_button_text',
                'label' => 'Button text',
                'name' => 'button_text',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => 'Get started',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_influencers_flex_hero_form_link',
                'label' => 'Form link',
                'name' => 'form_link',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                  array(
                    array(
                      'field' => 'field_influencers_flex_hero_cta_type',
                      'operator' => '==',
                      'value' => 'form',
                    ),
                  ),
                ),
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_influencers_flex_hero_utm_campaign',
                'label' => 'utm_campaign',
                'name' => 'utm_campaign',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                  array(
                    array(
                      'field' => 'field_influencers_flex_hero_cta_type',
                      'operator' => '==',
                      'value' => 'form',
                    ),
                  ),
                ),
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_influencers_flex_hero_caption',
                'label' => 'Caption',
                'name' => 'caption',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                  array(
                    array(
                      'field' => 'field_influencers_flex_hero_cta_type',
                      'operator' => '==',
                      'value' => 'form',
                    ),
                  ),
                ),
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_influencers_flex_hero_button_link',
                'label' => 'Button link',
                'name' => 'button_link',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                  array(
                    array(
                      'field' => 'field_influencers_flex_hero_cta_type',
                      'operator' => '==',
                      'value' => 'button',
                    ),
                  ),
                ),
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_influencers_flex_hero_right',
                'label' => 'Right',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
              ),
              array(
                'key' => 'field_influencers_flex_hero_type_of_media',
                'label' => 'Type of media',
                'name' => 'hero_type_of_media',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '30',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array(
                  'image' => 'Image',
                  'video' => 'Video',
                  'video_popup' => 'Video popup',
                ),
                'allow_null' => 0,
                'other_choice' => 0,
                'default_value' => '',
                'layout' => 'vertical',
                'return_format' => 'value',
                'save_other_choice' => 0,
              ),
              array(
                'key' => 'field_influencers_flex_hero_center_image',
                'label' => 'Center image',
                'name' => 'center_image',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                  array(
                    array(
                      'field' => 'field_influencers_flex_hero_type_of_media',
                      'operator' => '==',
                      'value' => 'image',
                    ),
                  ),
                ),
                'wrapper' => array(
                  'width' => '70',
                  'class' => '',
                  'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
              ),
              array(
                'key' => 'field_influencers_flex_hero_f_max_width',
                'label' => 'Max width of the front image',
                'name' => 'f_max_width',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                  array(
                    array(
                      'field' => 'field_influencers_flex_hero_type_of_media',
                      'operator' => '==',
                      'value' => 'image',
                    ),
                  ),
                ),
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '450px',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_influencers_flex_hero_b_max_width',
                'label' => 'Max width of the back image',
                'name' => 'b_max_width',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                  array(
                    array(
                      'field' => 'field_influencers_flex_hero_type_of_media',
                      'operator' => '==',
                      'value' => 'image',
                    ),
                  ),
                ),
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '450px',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_influencers_flex_hero_f_image',
                'label' => 'Front image',
                'name' => 'f_image',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                  array(
                    array(
                      'field' => 'field_influencers_flex_hero_type_of_media',
                      'operator' => '==',
                      'value' => 'image',
                    ),
                  ),
                ),
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'return_format' => 'id',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
              ),
              array(
                'key' => 'field_influencers_flex_hero_b_image',
                'label' => 'Back image',
                'name' => 'b_image',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                  array(
                    array(
                      'field' => 'field_influencers_flex_hero_type_of_media',
                      'operator' => '==',
                      'value' => 'image',
                    ),
                  ),
                ),
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'return_format' => 'id',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
              ),
              array(
                'key' => 'field_influencers_flex_hero_video',
                'label' => 'Hero video',
                'name' => 'hero_video',
                'type' => 'oembed',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                  array(
                    array(
                      'field' => 'field_influencers_flex_hero_type_of_media',
                      'operator' => '==',
                      'value' => 'video',
                    ),
                  ),
                ),
                'wrapper' => array(
                  'width' => '70',
                  'class' => '',
                  'id' => '',
                ),
                'width' => '',
                'height' => '',
              ),
              array(
                'key' => 'field_influencers_flex_hero_video_popup_link',
                'label' => 'Video link',
                'name' => 'video_popup_link',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                  array(
                    array(
                      'field' => 'field_influencers_flex_hero_type_of_media',
                      'operator' => '==',
                      'value' => 'video_popup',
                    ),
                  ),
                ),
                'wrapper' => array(
                  'width' => '70',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_influencers_flex_hero_video_popup_placeholder',
                'label' => 'Placeholder image',
                'name' => 'video_popup_placeholder',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                  array(
                    array(
                      'field' => 'field_influencers_flex_hero_type_of_media',
                      'operator' => '==',
                      'value' => 'video_popup',
                    ),
                  ),
                ),
                'wrapper' => array(
                  'width' => '100',
                  'class' => '',
                  'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
              ),
            ),
            'min' => '',
            'max' => '',
          ),
          'layout_influencers_flex_slider' => array(
            'key' => 'layout_influencers_flex_slider',
            'name' => 'flex_slider',
            'label' => 'Slider',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_influencers_flex_slider_hide_widget',
                'label' => 'Visibility',
                'name' => 'hide_widget',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'message' => 'Hide widget',
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
              ),
              array(
                'key' => 'field_influencers_flex_slider_widget_id',
                'label' => 'Widget ID',
                'name' => 'widget_id',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
              ),
              array(
                'key' => 'field_influencers_flex_slider_headline',
                'label' => 'Headline',
                'name' => 'headline',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
              ),
              array(
                'key' => 'field_influencers_flex_slider_subheadline',
                'label' => 'Subheadline',
                'name' => 'subheadline',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
              ),
              array(
                'key' => 'field_influencers_flex_slider_items',
                'label' => 'Items',
                'name' => 'items',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'layout' => 'block',
                'min' => 0,
                'max' => 0,
                'collapsed' => '',
                'button_label' => 'Add slide',
                'rows_per_page' => 20,
                'sub_fields' => array(
                  array(
                    'key' => 'field_influencers_flex_slider_items_title',
                    'label' => 'Title',
                    'name' => 'title',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_influencers_flex_slider_items',
                  ),
                  array(
                    'key' => 'field_influencers_flex_slider_items_answer',
                    'label' => 'Subtitle',
                    'name' => 'subtitle',
                    'aria-label' => '',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '50',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 1,
                    'delay' => 0,
                    'parent_repeater' => 'field_influencers_flex_slider_items',
                  ),
                  array(
                    'key' => 'field_influencers_flex_slider_items_image',
                    'label' => 'Image',
                    'name' => 'image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '50',
                      'class' => '',
                      'id' => '',
                    ),
                    'return_format' => 'array',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                  ),
                ),
              ),
              array(
                'key' => 'field_influencers_flex_slider_button_text',
                'label' => 'Button text',
                'name' => 'button_text',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => 'Get started',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_influencers_flex_slider_button_url',
                'label' => 'Button url',
                'name' => 'button_url',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),         
            ),
            'min' => '',
            'max' => '',
          ),
		      'layout_influencers_flex_customer_quote' => array(
            'key' => 'layout_influencers_flex_customer_quote',
            'name' => 'flex_customer_quote',
            'label' => 'Customer quote',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_influencers_flex_customer_quote_hide_widget',
                'label' => 'Visibility',
                'name' => 'hide_widget',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'message' => 'Hide widget',
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
              ),
              array(
                'key' => 'field_influencers_flex_customer_quote_widget_id',
                'label' => 'Widget ID',
                'name' => 'widget_id',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_influencers_flex_customer_quote_quote',
                'label' => 'Quote',
                'name' => 'quote',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => '',
              ),
              array(
                'key' => 'field_influencers_flex_customer_quote_image_bg',
                'label' => 'Background image',
                'name' => 'image_bg',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
              ),
              array(
                'key' => 'field_influencers_flex_customer_quote_image',
                'label' => 'Image',
                'name' => 'image',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
              ),
              array(
                'key' => 'field_influencers_flex_customer_quote_name',
                'label' => 'Name',
                'name' => 'name',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '33',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_influencers_flex_customer_quote_company',
                'label' => 'Company',
                'name' => 'company',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '34',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_influencers_flex_customer_quote_who_is',
                'label' => 'Who is',
                'name' => 'who_is',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '33',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
            ),
            'min' => '',
            'max' => '',
          ),
          'layout_influencers_flex_cta_banner' => array(
            'key' => 'layout_influencers_flex_cta_banner',
            'name' => 'flex_cta_banner',
            'label' => 'Footer CTA banner',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_influencers_flex_cta_banner_hide_widget',
                'label' => 'Visibility',
                'name' => 'hide_widget',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '25',
                  'class' => '',
                  'id' => '',
                ),
                'message' => 'Hide widget',
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
              ),              
              array(
                'key' => 'field_influencers_flex_cta_banner_align',
                'label' => 'Align',
                'name' => 'align',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '25',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array(
                  'left' => 'Left',
                  'center' => 'Center',
                ),
                'default_value' => 'left',
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
              ),
              array(
                'key' => 'field_influencers_flex_cta_banner_stype',
                'label' => 'Type',
                'name' => 'stype',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '25',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array(
                  'type1' => 'Type 1',
                  'type2' => 'Type 2',
                ),
                'default_value' => 'type1',
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
              ),
              array(
                'key' => 'field_influencers_flex_cta_banner_widget_id',
                'label' => 'Widget ID',
                'name' => 'widget_id',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '25',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_influencers_flex_cta_banner_content',
                'label' => 'Content',
                'name' => 'content',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 3,
                'new_lines' => '',
              ),
              array(
                'key' => 'field_influencers_cta_banner_items',
                'label' => 'Items',
                'name' => 'items',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'layout' => 'block',
                'min' => 0,
                'max' => 0,
                'collapsed' => '',
                'button_label' => 'Add Item',
                'rows_per_page' => 20,
                'sub_fields' => array(
                  array(
                    'key' => 'field_influencers_flex_cta_banner_items_item',
                    'label' => 'Item',
                    'name' => 'item',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_influencers_cta_banner_items',
                  ),
                ),
              ),
              array(
                'key' => 'field_influencers_flex_cta_banner_caption',
                'label' => 'Caption',
                'name' => 'caption',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_influencers_flex_cta_banner_button_text',
                'label' => 'Button text',
                'name' => 'button_text',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => 'Get started',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_influencers_flex_cta_banner_button_link',
                'label' => 'Button link',
                'name' => 'button_link',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
            ),
            'min' => '',
            'max' => '',
          ),
        ),
        'button_label' => 'Add Widget',
        'min' => '',
        'max' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'page_template',
          'operator' => '==',
          'value' => 'templates/flexible-influencers-lp.php',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
  ));
  
}

if ( function_exists('acf_add_local_field_group') ) add_action('acf/init', 'flexible_influencers_lp_acf_fields');  