<?php 

/*
 * Define Advanced Custom Fields for Homebase 
 */
function flexible_subscribe_mt192_fields() {
	acf_add_local_field_group(array(
		'key' => 'group_62ea91c6db4a8',
		'title' => 'Template: Subscribe MT192',
		'fields' => array(
			array(
				'key' => 'field_62ea9238427b2',
				'label' => 'Flexible content',
				'name' => 'flexible_content',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layouts' => array(
					'layout_62ea9260a4b01' => array(
						'key' => 'layout_62ea9260a4b01',
						'name' => 'header_settings',
						'label' => 'Header settings',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_subscribe_header_visibility',
								'label' => 'Hide widget',
								'name' => 'hide_widget',
								'type' => 'true_false',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 0,
								'ui' => 0,
								'ui_on_text' => '',
								'ui_off_text' => '',
							),
							array(
								'key' => 'field_62ea929a427b4',
								'label' => 'Headline',
								'name' => 'headline',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_62ea92af427b5',
								'label' => 'Subheadline',
								'name' => 'subheadline',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
				                'key' => 'field_subscribe_header_button_text',
				                'label' => 'Button Text',
				                'name' => 'button_text',
				                'type' => 'text',
				                'instructions' => '',
				                'required' => 0,
				                'conditional_logic' => 0,
				                'wrapper' => array(
				                  'width' => '50',
				                  'class' => '',
				                  'id' => '',
				                ),
				                'default_value' => 'Subscribe',
				                'placeholder' => '',
				                'prepend' => '',
				                'append' => '',
				                'maxlength' => '',
				              ),
				              array(
				                'key' => 'field_subscribe_header_form_link',
				                'label' => 'Form Link',
				                'name' => 'form_link',
				                'type' => 'text',
				                'instructions' => '',
				                'required' => 0,
				                'conditional_logic' => 0,
				                'wrapper' => array(
				                  'width' => '50',
				                  'class' => '',
				                  'id' => '',
				                ),
				                'default_value' => '',
				                'placeholder' => '',
				                'prepend' => '',
				                'append' => '',
				                'maxlength' => '',
				              ),
						),
						'min' => '',
						'max' => '',
					),
					'layout_62f3cec11831c' => array(
						'key' => 'layout_62f3cec11831c',
						'name' => 'flex_post_grid',
						'label' => 'Post grid',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_62f3cf5fbe7e1',
								'label' => 'Hide widget',
								'name' => 'hide_widget',
								'type' => 'true_false',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 0,
								'ui' => 0,
								'ui_on_text' => '',
								'ui_off_text' => '',
							),
							array(
								'key' => 'field_62f3cff8be7e2',
								'label' => 'Headline',
								'name' => 'headline',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_62f3d4d6be7e3',
								'label' => 'Custom posts',
								'name' => 'custom_posts',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'collapsed' => '',
								'min' => 3,
								'max' => 3,
								'layout' => 'table',
								'button_label' => '',
								'sub_fields' => array(
									array(
										'key' => 'field_62f3d7cdbe7e4',
										'label' => 'Custom post',
										'name' => 'custom_post',
										'type' => 'post_object',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'post_type' => '',
										'taxonomy' => '',
										'allow_null' => 0,
										'multiple' => 0,
										'return_format' => 'object',
										'ui' => 1,
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_62eac352bfcc5' => array(
						'key' => 'layout_62eac352bfcc5',
						'name' => 'customer_quote',
						'label' => 'Customer quote',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_subscribe_quote_visibility',
								'label' => 'Hide widget',
								'name' => 'hide_widget',
								'type' => 'true_false',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 0,
								'ui' => 0,
								'ui_on_text' => '',
								'ui_off_text' => '',
							),
							array(
								'key' => 'field_62eac37cbfcc6',
								'label' => 'Quote texts',
								'name' => 'quote_texts',
								'type' => 'textarea',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'maxlength' => '',
								'rows' => '',
								'new_lines' => '',
							),
							array(
								'key' => 'field_62eac396bfcc7',
								'label' => 'Name',
								'name' => 'name',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_62eac3b5bfcc8',
								'label' => 'Position',
								'name' => 'position',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_62eac3c2bfcc9' => array(
						'key' => 'layout_62eac3c2bfcc9',
						'name' => 'subscribe_line',
						'label' => 'Subscribe CTA',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_subscribe_cta_visibility',
								'label' => 'Hide widget',
								'name' => 'hide_widget',
								'type' => 'true_false',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 0,
								'ui' => 0,
								'ui_on_text' => '',
								'ui_off_text' => '',
							),
							array(
								'key' => 'field_62eac3d2bfcca',
								'label' => 'Section title',
								'name' => 'section_title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
				                'key' => 'field_subscribe_cta_button_text',
				                'label' => 'Button Text',
				                'name' => 'button_text',
				                'type' => 'text',
				                'instructions' => '',
				                'required' => 0,
				                'conditional_logic' => 0,
				                'wrapper' => array(
				                  'width' => '50',
				                  'class' => '',
				                  'id' => '',
				                ),
				                'default_value' => 'Subscribe',
				                'placeholder' => '',
				                'prepend' => '',
				                'append' => '',
				                'maxlength' => '',
				              ),
				              array(
				                'key' => 'field_subscribe_cta_form_link',
				                'label' => 'Form Link',
				                'name' => 'form_link',
				                'type' => 'text',
				                'instructions' => '',
				                'required' => 0,
				                'conditional_logic' => 0,
				                'wrapper' => array(
				                  'width' => '50',
				                  'class' => '',
				                  'id' => '',
				                ),
				                'default_value' => '',
				                'placeholder' => '',
				                'prepend' => '',
				                'append' => '',
				                'maxlength' => '',
				              ),
						),
						'min' => '',
						'max' => '',
					),
				),
				'button_label' => 'Add Row',
				'min' => '',
				'max' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_template',
					'operator' => '==',
					'value' => 'templates/flexible-subscribe-mt192.php',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));
}

if ( function_exists('acf_add_local_field_group') ) add_action('acf/init', 'flexible_subscribe_mt192_fields');  