<?php 

/*
 * Define Advanced Custom Fields for Single Blog posts 
 */

function flexible_blog_post_fields() {

acf_add_local_field_group(array(
	'key' => 'group_621d0e7b36043',
	'title' => 'Template: Blog',
	'fields' => array(
		array(
			'key' => 'field_622f879889425',
			'label' => 'Meet the owners',
			'name' => 'meet_the_owners',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_622f8a5801e5a',
					'label' => 'Visibility',
					'name' => 'mto_hide_widget',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Hide widget',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array(
					'key' => 'field_622f87f989426',
					'label' => 'Meet the owners (row)',
					'name' => 'meet_the_owners_row',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'block',
					'button_label' => '',
					'sub_fields' => array(
						array(
							'key' => 'field_622f880f89427',
							'label' => 'Image',
							'name' => 'mto_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_622f881d89428',
							'label' => 'Name',
							'name' => 'mto_name',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_622f8bd201e5b',
							'label' => 'Company',
							'name' => 'mto_company',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '40',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_622f8bec01e5c',
							'label' => 'Text',
							'name' => 'mto_text',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => '',
						),
					),
				),
			),
		),
		array(
			'key' => 'field_622f882c89429',
			'label' => 'FAQ',
			'name' => 'blog_faq',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_622f8cc491374',
					'label' => 'Visibility',
					'name' => 'blog_faq_hide_widget',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Hide widget',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array(
	                'key' => 'field_blog_faq_left',
	                'label' => 'Left',
	                'name' => '',
	                'type' => 'tab',
	                'instructions' => '',
	                'required' => 0,
	                'conditional_logic' => 0,
	                'wrapper' => array(
	                  'width' => '',
	                  'class' => '',
	                  'id' => '',
	                ),
	                'placement' => 'top',
	                'endpoint' => 0,
	            ),
              	array(
	                'key' => 'field_blog_faq_headline',
	                'label' => 'Headline',
	                'name' => 'blog_faq_headline',
	                'type' => 'text',
	                'instructions' => '',
	                'required' => 0,
	                'conditional_logic' => 0,
	                'wrapper' => array(
	                  'width' => '',
	                  'class' => '',
	                  'id' => '',
	                ),
	                'default_value' => '',
	                'placeholder' => '',
	                'prepend' => '',
	                'append' => '',
	                'maxlength' => '',
	            ),
              	array(
	                'key' => 'field_blog_faq_image_d',
	                'label' => 'Image (Desktop)',
	                'name' => 'blog_faq_image_d',
	                'type' => 'image',
	                'instructions' => '',
	                'required' => 0,
	                'conditional_logic' => 0,
	                'wrapper' => array(
	                  'width' => '50',
	                  'class' => '',
	                  'id' => '',
	                ),
	                'return_format' => 'id',
	                'preview_size' => 'medium',
	                'library' => 'all',
	                'min_width' => '',
	                'min_height' => '',
	                'min_size' => '',
	                'max_width' => '',
	                'max_height' => '',
	                'max_size' => '',
	                'mime_types' => '',
	            ),
	            array(
	                'key' => 'field_blog_faq_image_m',
	                'label' => 'Image (Mobile)',
	                'name' => 'blog_faq_image_m',
	                'type' => 'image',
	                'instructions' => '',
	                'required' => 0,
	                'conditional_logic' => 0,
	                'wrapper' => array(
	                  'width' => '50',
	                  'class' => '',
	                  'id' => '',
	                ),
	                'return_format' => 'id',
	                'preview_size' => 'medium',
	                'library' => 'all',
	                'min_width' => '',
	                'min_height' => '',
	                'min_size' => '',
	                'max_width' => '',
	                'max_height' => '',
	                'max_size' => '',
	                'mime_types' => '',
	            ),
	            array(
	                'key' => 'field_blog_faq_right',
	                'label' => 'Right',
	                'name' => '',
	                'type' => 'tab',
	                'instructions' => '',
	                'required' => 0,
	                'conditional_logic' => 0,
	                'wrapper' => array(
	                  'width' => '',
	                  'class' => '',
	                  'id' => '',
	                ),
	                'placement' => 'top',
	                'endpoint' => 0,
	            ),
				array(
					'key' => 'field_622f88558942a',
					'label' => 'FAQ (row)',
					'name' => 'blog_faq_row',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'block',
					'button_label' => '',
					'sub_fields' => array(
						array(
		                    'key' => 'field_blog_faq_field',
		                    'label' => 'FAQ field',
		                    'name' => 'blog_faq_field',
		                    'type' => 'text',
		                    'instructions' => '',
		                    'required' => 0,
		                    'conditional_logic' => 0,
		                    'wrapper' => array(
		                      'width' => '',
		                      'class' => '',
		                      'id' => '',
		                    ),
		                    'default_value' => '',
		                    'placeholder' => '',
		                    'prepend' => '',
		                    'append' => '',
		                    'maxlength' => '',
		                ),
						array(
							'key' => 'field_blog_faq_question',
							'label' => 'Question',
							'name' => 'blog_faq_question',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_blog_faq_answer',
							'label' => 'Answer',
							'name' => 'blog_faq_answer',
							'type' => 'wysiwyg',
		                    'instructions' => '',
		                    'required' => 0,
		                    'conditional_logic' => 0,
		                    'wrapper' => array(
		                      'width' => '',
		                      'class' => '',
		                      'id' => '',
		                    ),
		                    'default_value' => '',
		                    'tabs' => 'all',
		                    'toolbar' => 'full',
		                    'media_upload' => 1,
		                    'delay' => 0,
						),
					),
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

}

if ( function_exists('acf_add_local_field_group') ) add_action('acf/init', 'flexible_blog_post_fields'); 


function hero_banner_new_blog_post_fields() {

acf_add_local_field_group(array(
	'key' => 'group_6255bcb54b91d',
	'title' => 'Hero Banner New',
	'fields' => array(
		array(
			'key' => 'field_6255bcd5dcefe',
			'label' => 'Image',
			'name' => 'hero_banner_new_image',
			'type' => 'image',
			'instructions' => 'Watch this video to see how it works: <a href="https://somup.com/c3flqTOqxx" target="_blank">https://somup.com/c3flqTOqxx</a>',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_cd8sic7s98cd7s',
			'label' => 'Display Publish Date',
			'name' => 'hb_display_publish_date',
			'type' => 'true_false',
			'instructions' => 'Enable this option will display publish date. on frontend & SEO meta.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
));


}

if ( function_exists('acf_add_local_field_group') ) add_action('acf/init', 'hero_banner_new_blog_post_fields'); 
	