<?php 

/**** Requiere Custom Fileds */
require_once('homebase-acfs/body-class-fields.php');
require_once('homebase-acfs/flexible-home-mt39-v1.0-fields.php');
require_once('homebase-acfs/flexible-home-mt39-v2.0-fields.php');
require_once('homebase-acfs/blog-option-fields.php');
require_once('homebase-acfs/engineering-option-fields.php');
require_once('homebase-acfs/post-category-fields.php');
require_once('homebase-acfs/flexible-content-fields.php');
require_once('homebase-acfs/flexible-data-covid19-fields.php');
require_once('homebase-acfs/flexible-feature-mt51-fields.php');
require_once('homebase-acfs/flexible-careers-mt104-fields.php');
require_once('homebase-acfs/flexible-franchise-mt93-fields.php');
require_once('homebase-acfs/flexible-press-mt63-fields.php');
require_once('homebase-acfs/flexible-partners4-mt66-fields.php');
require_once('homebase-acfs/flexible-support-mt55-fields.php');
require_once('homebase-acfs/flexible-pricing-mt58-fields.php');
require_once('homebase-acfs/flexible-partners-mt50-fields.php');
require_once('homebase-acfs/flexible-cobranded-partner-mt69-fields.php');
require_once('homebase-acfs/flexible-customer-mt54-fields.php');
require_once('homebase-acfs/flexible-customers-table-mt65-fields.php');
require_once('homebase-acfs/flexible-competitor-mt57-fields.php');
require_once('homebase-acfs/flexible-seo-cluster-mt87-fields.php');
require_once('homebase-acfs/flexible-simplified-paid-mt31-fields.php');
require_once('homebase-acfs/flexible-time-card-calculator-mt88-fields.php');
require_once('homebase-acfs/flexible-pricing-mt120-fields.php');
require_once('homebase-acfs/flexible-pricing-wp977-fields.php');
require_once('homebase-acfs/flexible-secure-mt131-fields.php');
require_once('homebase-acfs/flexible-aboutus-mt62-fields.php');
require_once('homebase-acfs/flexible-labor-law-mt120-fields.php');
require_once('homebase-acfs/flexible-video-lp-mm-fields.php');
require_once('homebase-acfs/flexible-payroll-testimonial-fields.php');
require_once('homebase-acfs/flexible-blog-post-fields.php');
require_once('homebase-acfs/flexible-contact-sales-mt64-fields.php');
require_once('homebase-acfs/flexible-subscribe-mt192-fields.php');
require_once('homebase-acfs/flexible-subscribe-success-mt192-fields.php');
require_once('homebase-acfs/flexible-fow-microsite-fields.php');
require_once('homebase-acfs/flexible-pay-any-day-lp-fields.php');
require_once('homebase-acfs/flexible-direct-mail-lp-fields.php');
require_once('homebase-acfs/flexible-scheduling-fields.php');
require_once('homebase-acfs/flexible-influencers-lp-fields.php');
require_once('homebase-acfs/cro-popup-fields.php');
require_once('homebase-acfs/email-capture-popup-fields.php');
require_once('homebase-acfs/cro-sticky-banner-fields.php');
require_once('homebase-acfs/bloglike-fields.php');
require_once('homebase-acfs/flexible-NSBW-campaign-fields.php');
require_once('homebase-acfs/flexible-time-card-calculator-v2-fields.php');
require_once('homebase-acfs/custom-script-after-footer-fields.php');
//require_once('include/ajax-functions.php'); 

?>